#<This file exists to avoid cyclic imports and allow the application windows be managed by the Controller and communicate back to the controller>

from typing import Protocol, List


import sys
sys.path.append('../')
from communication_protocol.TCPMessages import *
sys.path.append('client/')


class Controller(Protocol):
    username: str
    current_channel_id: int
    
    def add_binding(self, key: str, func: callable) -> None: ...
    
    def switch_frame(self, frame_name: str) -> None: ...

    def recieve_incoming_msg(self, msg: NewMessageNotif) -> None: ...

    def get_outgoing_msgs(self) -> List[TCPMessage]: ...

    def add_outgoing_text_msg(self, content: str) -> None: ...
    
    def add_message_internal(self, content) -> None: ...

    def close() -> None: ...

    def channel_create_request(self, channel_name: str): ...
    
    def add_channel(self, channel_id: int, channel_name: str): ...

    def switch_channel(self, channel_id: int): ...

    def channel_join_request(self, channel_id: int): ...

    def user_join_channel_update(self, channel_id: int, username: str) -> None: ...

    def create_channel(self, channel_id: int, channel_name: str) -> None: ...

    def join_channel(self, channel_id: int, channel_name: str) -> None: ...

    def get_suggestions(self, prefix: str) -> List[str]: ...

    def attempt_login(self, name: str) -> None: ...

    def login_approved(self, user_id: int) -> None: ...

    def on_suggestion_press(self, suggestioNo): ...