#<This file exists to avoid cyclic imports and allow the application windows be managed by the Controller and communicate back to the controller>

from typing import Protocol, List

class Controller(Protocol):
    def switch_frame(self, frame_name: str) -> None: ...

    def recieve_incoming_msg(msg: dict) -> None: ...

    def get_outgoing_msgs() -> List[str]: ...

    def add_outgoing_msg(msgs: dict) -> None: ...
    
    def close() -> None: ...